Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 

Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. 

Будем считать, что каждый столбец - это признак, а строка - наблюдение. 

Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 

Результат запишите в массив mean_a, в нем должно быть 2 элемента.


# Задание 1

In [3]:
import numpy as np

In [4]:
a = np.array([
[1, 6],
[2, 8],
[3, 11],
[3, 10],
[1, 7],
])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

# Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения 
соответствующих признаков, содержащиеся в массиве mean_a. 
Вычисление должно производиться в одно действие. 
Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a.reshape(1,2)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.
*!!столбец - это признак, а строка - наблюдение!!*


In [7]:
a1 = a_centered[:, 0]
a1

array([-1.,  0.,  1.,  1., -1.])

In [8]:
a2 = a_centered[:, 1]
a2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [9]:
a_centered_sp = a1@a2
a_centered_sp

8.0

In [10]:
N = a.shape[0]
N

5

In [11]:
total = a_centered_sp / (N - 1)
total

2.0

In [12]:
c = np.cov(a.transpose())
c

array([[1. , 2. ],
       [2. , 4.3]])

In [13]:
cavariation = c[1, 0]
cavariation

2.0

# Работа с данными в Pandas


# Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].


In [14]:
import pandas as pd 

In [15]:
a = {
    "author_id": [1, 2, 3],
    "author_name": ["Тургенев'", "Чехов", "Островский"]
}
authors = pd.DataFrame(a)
authors

author_id author_name
0          1   Тургенев'
1          2       Чехов
2          3  Островский

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [16]:
c = {
    "author_id" : [1, 1, 1, 2, 2, 3, 3],
    "book_title" : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price" : [450, 300, 350, 500, 450, 370, 290]
}
books = pd.DataFrame(c)
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

# Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [17]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1   Тургенев'           Отцы и дети    450
1          1   Тургенев'                 Рудин    300
2          1   Тургенев'     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290



# Задание 3


Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [18]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1   Тургенев'        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1   Тургенев'  Дворянское гнездо    350

# Задание 4


Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [19]:
df1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'}) 
df3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
df1, df2, df3 

(             min_price
 author_name           
 Островский         290
 Тургенев'          300
 Чехов              450,
              max_price
 author_name           
 Островский         370
 Тургенев'          450
 Чехов              500,
              mean_price
 author_name            
 Островский   330.000000
 Тургенев'    366.666667
 Чехов        475.000000)

In [20]:
authors_stat = pd.concat([df1, df2, df3], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев'          300        450  366.666667
Чехов              450        500  475.000000

# Задание 5**
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [21]:
df1 = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']}, columns=['cover'])
authors_price = pd.concat([authors_price, df1], axis = 1)
authors_price

author_id author_name            book_title  price    cover
0          1   Тургенев'           Отцы и дети    450  твердая
1          1   Тургенев'                 Рудин    300   мягкая
2          1   Тургенев'     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [34]:
?pd.pivot_table

In [25]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев'       650      450
Чехов             0      950

In [27]:
book_info.to_pickle('book_info.pkl')

In [33]:
book_info2 = pd.read_pickle('book_info.pkl')

In [30]:
book_info==book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев'      True     True
Чехов          True     True